# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bb6447f23033725c02c2c75d9ebe1a483c583eb016b4d90c091502d27418f0b73d45578052415e910c981c98d90b984557f7ffaa044c86d142078bbb18c0f31

test:
  secret_key_base: c1a783d621188712dc883095b1cc668f9007aebc42b6ce67ddd99f75aeb9415b933e7a50f0ae43ba58a33b708ebe96f556e559706259841d5174505a4e2e1337

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
